import { page, download, robot, assert, FX } from '../lib/harness.mjs';
export default async function (env) {
  const r = robot('Sign Master'); const p = await page(env, 'signmaster.html');
  await r.check('assinatura carregada → PNG transparente', async () => { await p.evaluate(() => nav('upload-sig', null)); await p.setInputFiles('#page-upload-sig input[type=file]', FX + '/sig.jpg'); await p.waitForTimeout(800); const d = await download(p, () => p.click('#page-upload-sig button.btn-primary')); assert(d, 'sem download'); const a = await p.evaluate(async a => { const bm = await createImageBitmap(new Blob([new Uint8Array(a)])); const c = document.createElement('canvas'); c.width = bm.width; c.height = bm.height; const x = c.getContext('2d'); x.drawImage(bm, 0, 0); const d = x.getImageData(0, 0, c.width, c.height).data; let t = 0; for (let i = 3; i < d.length; i += 4) if (d[i] === 0) t++; return t / (d.length / 4); }, [...d.buf]); assert(a > 0.5, 'pouco transparente: ' + a); return Math.round(a * 100) + '% transparente'; });
  for (const id of ['draw', 'type', 'initials']) await r.check(id, async () => { await p.evaluate(id => nav(id, null), id); if (id === 'type') await p.fill('#page-type input[type=text]', 'Yanick Silva').catch(() => {}); if (id === 'draw') { const c = p.locator('#page-draw canvas').first(); const b = await c.boundingBox(); await p.mouse.move(b.x + 20, b.y + 20); await p.mouse.down(); await p.mouse.move(b.x + 120, b.y + 60); await p.mouse.up(); } const d = await download(p, () => p.locator(`#page-${id} button.btn-primary`).first().click(), 10000); assert(d, 'sem download'); return d.name; });
  await r.check('assinar imagem', async () => { await p.evaluate(() => nav('sign-img', null)); await p.setInputFiles('#page-sign-img input[type=file]', FX + '/photo.jpg'); await p.waitForTimeout(600); const d = await download(p, () => p.click('#page-sign-img button.btn-primary'), 10000); assert(d, 'sem download'); return d.name; });
  await r.check('assinar PDF', async () => { await p.evaluate(() => nav('sign-pdf', null)); await p.setInputFiles('#spdf-input', FX + '/a.pdf'); await p.waitForTimeout(800); await p.click('#spdf-type-btn'); await p.fill('#spdf-type-name', 'Yanick Silva'); await p.click('text=Continuar → Posicionar assinatura'); await p.waitForTimeout(1500); await p.locator('#spdf-pages canvas').first().click({ position: { x: 120, y: 150 } }).catch(() => {}); const d = await download(p, () => p.locator('#spdf-s3 button.btn-primary').last().click(), 20000); assert(d, 'sem download — ' + (await p.textContent('#spdf-status')).trim()); const imgs = await p.evaluate(async a => { const doc = await pdfjsLib.getDocument({ data: new Uint8Array(a) }).promise; const ops = await (await doc.getPage(1)).getOperatorList(); return ops.fnArray.filter(f => f === pdfjsLib.OPS.paintImageXObject).length; }, [...d.buf]); assert(imgs >= 1, 'assinatura não está no PDF'); return 'ok'; });
  await r.check('sem erros JS', async () => { assert(!p.errors.length, p.errors.join(' | ')); return 'ok'; });
  await p.close(); return r;
}
