import fs from 'fs'; import path from 'path'; import { page, download, robot, assert, TOOLS_DIR } from '../lib/harness.mjs';
export default async function (env) {
  const r = robot('QR Master'); const p = await page(env, 'qrmaster.html');
  await p.addScriptTag({ content: fs.readFileSync(path.join(TOOLS_DIR, 'tests/lib/jsQR.js'), 'utf8') });
  const decode = () => p.evaluate(() => { const c = document.getElementById('render-canvas'); const q = jsQR(c.getContext('2d').getImageData(0, 0, c.width, c.height).data, c.width, c.height); return q ? q.data : null; });
  async function gen(type, fields) { await p.evaluate(t => setType(t, document.querySelector(`[onclick*="setType('${t}'"]`)), type); for (const [id, v] of Object.entries(fields)) await p.fill('#' + id, v); await p.evaluate(() => { document.getElementById('render-canvas').getContext('2d').clearRect(0, 0, 9999, 9999); generateQR(); }); await p.waitForTimeout(400); return decode(); }
  const cases = [['url', { 'i-url': 'https://imoauto.cv' }, 'https://imoauto.cv'], ['text (acentos)', { 'i-text': 'Olá Cabo Verde — ção' }, 'Olá Cabo Verde — ção'], ['wifi', { 'i-wifi-ssid': 'Casa;Yax', 'i-wifi-pass': 'se:nha;123' }, String.raw`WIFI:T:WPA;S:Casa\;Yax;P:se\:nha\;123;;`], ['vcard', { 'i-vc-name': 'Yanick Silva', 'i-vc-phone': '+238 999 99 99' }, 'BEGIN:VCARD'], ['event', { 'i-ev-name': 'Lançamento', 'i-ev-start': '2026-10-01T14:00', 'i-ev-end': '2026-10-01T16:00' }, 'BEGIN:VCALENDAR'], ['location', { 'i-lat': '14.9331', 'i-lng': '-23.5133' }, 'query=14.9331,-23.5133'], ['whatsapp', { 'i-wa-num': '+238 999 99 99', 'i-wa-msg': 'Olá!' }, 'wa.me/2389999999']];
  for (const [name, f, expect] of cases) await r.check(name, async () => { const t = await gen(name.split(' ')[0], f); assert(t && t.includes(expect), 'lido: ' + t); return 'lê'; });
  await r.check('24 formas legíveis', async () => { await p.evaluate(() => setType('url', document.querySelector(`[onclick*="setType('url'"]`))); await p.fill('#i-url', 'https://imoauto.cv/anuncios/casa-praia-palmarejo-3-quartos-com-vista-mar?ref=qr'); const bad = []; for (const m of ['square', 'dot', 'rounded', 'diamond', 'star', 'vertical']) for (const e of ['square', 'circle', 'rounded', 'leaf']) { await p.evaluate(([m, e]) => { document.querySelector(`input[name=mod-shape][value=${m}]`).checked = true; document.querySelector(`input[name=eye-shape][value=${e}]`).checked = true; generateQR(); }, [m, e]); await p.waitForTimeout(200); if (!await decode()) bad.push(m + '/' + e); } assert(!bad.length, 'ilegíveis: ' + bad.join(', ')); return '24/24'; });
  await r.check('SVG vetorial legível', async () => { const d = await download(p, () => p.evaluate(() => downloadSVGFile())); const svg = d.buf.toString(); assert(!svg.includes('<image'), 'SVG com PNG embutido'); const t = await p.evaluate(async s => { const img = new Image(); img.src = 'data:image/svg+xml;base64,' + btoa(unescape(encodeURIComponent(s))); await img.decode(); const c = document.createElement('canvas'); c.width = c.height = 600; const x = c.getContext('2d'); x.fillStyle = '#fff'; x.fillRect(0, 0, 600, 600); x.drawImage(img, 0, 0, 600, 600); const q = jsQR(x.getImageData(0, 0, 600, 600).data, 600, 600); return q && q.data; }, svg); assert(t, 'SVG não lê'); return 'ok'; });
  await r.check('campo vazio dá aviso (não QR falso)', async () => { await p.evaluate(() => setType('menu', document.querySelector(`[onclick*="setType('menu'"]`))); await p.fill('#i-menu-url', ''); await p.evaluate(() => generateQR()); const t = await p.evaluate(() => document.getElementById('qr-toast')?.textContent || ''); assert(t.includes('link'), 'sem aviso'); return t; });
  await r.check('sem erros JS', async () => { assert(!p.errors.length, p.errors.join(' | ')); return 'ok'; });
  await p.close(); return r;
}
